on:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository == 'nix-community/home-manager'
    steps:
      - uses: mschilde/auto-label-merge-conflicts@3fdaf1c8b3f8e5b0f88753d9cb3c9c779370b3ef # master 2026-09-14
        with:
          CONFLICT_LABEL_NAME: "merge conflict"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 10000
